src/Novell.Directory.Ldap.NETStandard/AsyncExtensions.cs, src/Novell.Directory.Ldap.NETStandard/Connection.cs, src/Novell.Directory.Ldap.NETStandard/LdapConnection.cs
This adds an explicit connection timeout. Windows seems to automatically timeout requests after 3 sec but on Linux/Mono it can take over 2 minutes for the automatic timeout. This gives you the ability to specify a value directly, however only values less than the automatic timeout will have any affect.
=> Add connection timeout

src/Novell.Directory.Ldap.NETStandard/Connection.cs, src/Novell.Directory.Ldap.NETStandard/LdapConnection.cs
Allows client to attach certificates.
This has been tested using a pfx file and has succeeded in connecting, binding & searching a remote secure LDAP server
=> Enable local certificate validation callbacks. 

src/Novell.Directory.Ldap.NETStandard/SupportClass.ThreadClass.cs
Correct a typo in the parameter.
Change the calculations for Thread.Join(int32) to use milliseconds.
Should this be removed as .NET doesn't support the nanosecond resolution? Or should it be changed to use a TimeSpan instead?
https://github.com/Kim-SSi/Novell.Directory.Ldap.NETStandard/blob/threadfix/src/Novell.Directory.Ldap.NETStandard/SupportClass.ThreadClass.cs#L185-L196
=> Fix parameter typo and thread join timeout calculations

src/Novell.Directory.Ldap.NETStandard/Connection.cs
This PR adds a check to `Connection.Connect(string host, int port, int semaphoreId)` to determine if `host` is already an IP address. In the case that `host` is an IP, then skip the DNS lookup.
I have a use case in which I am using an IP address specifically to prevent a DNS lookup. In my case, a fallback DNS server is expected to be down. If a DNS lookup occurs the DNS timeout must elapse before continuing with the LDAP connection. In my case this is causing the connection to take around 8 seconds. Skipping the DNS lookup in the case that an IP is provided fixes the issue.
Thanks.
=> Prevents dns lookup if IP is passed to Connect

src/Novell.Directory.Ldap.NETStandard/Connection.cs
=> Always dispose _sock and _socket if and only if they have been set

src/Novell.Directory.Ldap.NETStandard/Controls/ExtendedDnControl.cs
Extended DN Control is used with an extended LDAP search to request an extended form of object Distinguished Name. The extended form includes a string representation of Object GUID along with Distinguished Name of the object.
`<GUID=xxxxxxxx>;distinguishedName`
```
LdapSearchConstraints cons = _ldapConnection.SearchConstraints;
var guidAsString = new ExtendedDnControl(ExtendedDnControl.GuidFormatFlag.String, true);
cons.SetControls(guidAsString);
```
GuidFormatFlag can be `Hex` or `String` - LDAP GUID format in HEX or string dashed format.
I made port from java code based [this](https://community.microfocus.com/t5/eDirectory-Tips-Information/How-to-use-the-LDAP-Extended-DN-Control-with-LDAP-classes-for/ta-p/2701121#) article.  All credit goes to [idsecurity](https://github.com/idsecurity)
=> Support for  ExtendedDnControl

src/Novell.Directory.Ldap.NETStandard/Connection.cs
In cases where we don't specify a timeout, WaitAndUnwrap serves no purpose (i.e. it behaves in the same way as the blocking call) and allocates extra threads that negatively impact performance.
The code now prefers the sync call when  is unset to avoid the extra threads
=> Avoid unnecessary async calls

src/Novell.Directory.Ldap.NETStandard/Rfc2251/RfcFilter.cs, src/Novell.Directory.Ldap.NETStandard/Utilclass/StringExtensions.cs, test/Novell.Directory.Ldap.NETStandard.UnitTests/StringExtensionTests.cs
We are sometimes using large filters to query information about a lot of active directory groups at once (up to 200 groups). When I developed on my windows machine, the performance was alright and I had the response in about 40ms. When I deployed the .NET Core 3.1 Webservice to a linux machine, the duration for one query went **up to one second**. 
After a lot of performance measuring I figured out that the culprit was the huge number of called `_filter.Substring(_offset).StartsWith(...)` while parsing the filter. This code is much less performant on Linux than on Windows. Besides that there are a lot of memory allocations which can be avoided.
So I replaced those lines with an index based method `StartsWithStringAtOffset`, which I implemented as an extension method on string.
I only …
=> Huge performance increase in filter parsing

src/Novell.Directory.Ldap.NETStandard/Controls/LdapPagedResultsControl.cs, src/Novell.Directory.Ldap.NETStandard/Novell.Directory.Ldap.NETStandard.csproj, src/Novell.Directory.Ldap.NETStandard/Utilclass/PagedResultsControlHandler.cs, src/Novell.Directory.Ldap.NETStandard/Utilclass/SearchOptions.cs
LDAP Control Extension for Simple Paged Results Manipulation (RFC 2629) support
Sometimes we need to retrieve large search result set (for example, 100 000 entries). This case we may face some troubles:
- there are limits set on the LDAP server as when using Microsoft Active Directory and MaxPageSize is exceeded
- low-bandwidth connection
- the LDAP client has limited resources
The simple paged results control can be attached to a search operation to indicate that only a subset of the results should be returned. It may be used to iterate through the search results at a time. It is similar to virtual list view control but does not require the result set to be sorted and provides only the ability to iterate sequentially through the result set.
=> LdapPagedResultsControl.cs & PagedResultsControlHandler.cs

src/Novell.Directory.Ldap.NETStandard/LdapConnection.Sasl.cs, src/Novell.Directory.Ldap.NETStandard/Sasl/Clients/BaseSaslClient.cs, src/Novell.Directory.Ldap.NETStandard/Sasl/Clients/CramMD5Client.cs, src/Novell.Directory.Ldap.NETStandard/Sasl/Clients/DigestMD5Client.cs, src/Novell.Directory.Ldap.NETStandard/Sasl/Clients/PlainClient.cs, src/Novell.Directory.Ldap.NETStandard/Sasl/ISaslClient.cs, test/Novell.Directory.Ldap.NETStandard.UnitTests/CramMD5ClientTests.cs, test/Novell.Directory.Ldap.NETStandard.UnitTests/PlainClientTests.cs, test/Novell.Directory.Ldap.NETStandard.UnitTests/TestSaslClient.cs
Ideally, I believe all Bind methods should be async (or at least have an async variant), but for implementing some custom based Sasl clients which acts asynchronously (aka receive data to feed via EvaluateChallenge asynchronously - ie via a network, for example) the async is really a must have.
This might break a bit backward compatibility (because of interface changes), but I tried to make the port to be as harmless as possible (at least I hope). I kept all the old synchronized methods as is without changing their behaviour (I believe).
=> Making Sasl Bind async for advanced Sasl clients

src/Novell.Directory.Ldap.NETStandard/Connection.cs, src/Novell.Directory.Ldap.NETStandard/MessageAgent.cs, src/Novell.Directory.Ldap.NETStandard/MessageVector.cs
As it was reported already (https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/130) the `MessageVector` class 
had the race condition. This PR fixes it and also makes sure that there is locking around all remaining `MessageVector` methods. Note, that I've decided to use composition instead of inheritance for better control of which methods of the `ArrayList` type are used.
=> Make the MessageVector to be thread safe

src/Novell.Directory.Ldap.NETStandard/SupportClass.cs
`SupportClass.VectorRemoveElement` has public signature, but it is very unlikely anyone uses it in external code so I think it is ok to remove it.
=> Remove the unused method `SupportClass.VectorRemoveElement`

src/Novell.Directory.Ldap.NETStandard/AsyncExtensions.cs, src/Novell.Directory.Ldap.NETStandard/Connection.cs, src/Novell.Directory.Ldap.NETStandard/ILdapConnection.ExtensionMethods.cs, src/Novell.Directory.Ldap.NETStandard/LdapConnection.Sasl.cs, src/Novell.Directory.Ldap.NETStandard/LdapConnection.cs, src/Novell.Directory.Ldap.NETStandard/LdapSearchResults.cs, src/Novell.Directory.Ldap.NETStandard/Message.cs, src/Novell.Directory.Ldap.NETStandard/SearchExtensions/SimplePagedResultsControlHandler.cs, src/Novell.Directory.Ldap.NETStandard/SearchExtensions/VirtualListViewControlHandler.cs
A library should always use `.ConfigureAwait(false)`
Here is a nice FAQ for this topic: https://devblogs.microsoft.com/dotnet/configureawait-faq/#when-should-i-use-configureawaitfalse
> This leads to the general guidance of: if you’re writing general-purpose library code, use ConfigureAwait(false). This is why, for example, you’ll see every (or almost every) await in the .NET Core runtime libraries using ConfigureAwait(false) on every await; with a few exceptions, in cases where it doesn’t it’s very likely a bug to be fixed.
=> Add .ConfigureAwait(false) to all await statements

README.md, src/Novell.Directory.Ldap.NETStandard/ILdapConnection.ExtensionMethods.cs, src/Novell.Directory.Ldap.NETStandard/ILdapSearchResults.cs, src/Novell.Directory.Ldap.NETStandard/LdapConnection.cs, src/Novell.Directory.Ldap.NETStandard/LdapExtensions/ExtensionRegistrations.cs, src/Novell.Directory.Ldap.NETStandard/LdapSearchResults.cs, src/Novell.Directory.Ldap.NETStandard/Novell.Directory.Ldap.NETStandard.csproj, src/Novell.Directory.Ldap.NETStandard/SearchExtensions/SimplePagedResultsControlHandler.cs, src/Novell.Directory.Ldap.NETStandard/SearchExtensions/SimplePagedResultsControlSearchExtensions.cs, src/Novell.Directory.Ldap.NETStandard/SearchExtensions/VirtualListViewControlHandler.cs, src/Novell.Directory.Ldap.NETStandard/SearchExtensions/VirtualListViewControlSearchExtensions.cs, test/Novell.Directory.Ldap.NETStandard.FunctionalTests/SearchTests.cs
This will drop support for .netstandard 1.3 and will use IAsyncEnumerable in LdapSearchResults to get rid of .GetAwaiter for this.
Solves issue: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/155
=> Move ILdapSearchResults to async (implement IAsyncEnumerable instead of IEnumerable)

src/Novell.Directory.Ldap.NETStandard/Novell.Directory.Ldap.NETStandard.csproj, src/Novell.Directory.Ldap.NETStandard/SearchExtensions/SimplePagedResultsControlHandler.cs, src/Novell.Directory.Ldap.NETStandard/SearchExtensions/VirtualListViewControlHandler.cs, src/Novell.Directory.Ldap.NETStandard/Utilclass/AsyncEnumerableExtensions.cs, test/Novell.Directory.Ldap.NETStandard.FunctionalTests/SearchTests.cs
System.Linq.Async appears to be used exclusively to provide ToListAsync, which is ridiculous as it is trivial to implement.
It also introduces extension methods into the System.Linq namespace which conflict with common EntityFrameworkCore usage patterns, as DbSet&lt;T&gt; implements both IAsyncEnumerable&lt;T&gt; and IQueryable&lt;T&gt;. This most often manifests itself as a conflict between:
```cs
System.Linq.AsyncEnumerable.Where<T>(this IAsyncEnumerable<T>, Func<T, bool>)
```
and
```cs
System.Linq.Queryable.Where(this IQueryable<T>, Expression<Func<T, bool>>)
```
You can watch both Microsoft teams blame each other here:
https://github.com/dotnet/reactive/issues/1057
https://github.com/dotnet/efcore/issues/18124
=> Remove dependency on System.Linq.Async

src/Novell.Directory.Ldap.NETStandard/Utilclass/AsyncEnumerableExtensions.cs, test/Novell.Directory.Ldap.NETStandard.FunctionalTests/Novell.Directory.Ldap.NETStandard.FunctionalTests.csproj
Change the access modifier for AsyncEnumerableExtensions.ToListAsync from `public` to `internal`.
Doing this removes ambiguity in projects dependent on System.Linq.Async to utilize ILdapSearchResults..
Additionally add dependency on System.Linq.Async for FunctionalTests to maintain functionality.
Closes #250.
=> Change access modifier for AsyncEnumerableExtensions.ToListAsync

src/Novell.Directory.Ldap.NETStandard/Tokenizer.cs, test/Novell.Directory.Ldap.NETStandard.UnitTests/TokenizerTests.cs
I reworked Tokenizer, trying to remove the repeated splitting, as the elements were all already there and utilizing the built-in `StringSplitOptions.RemoveEmptyEntries`.
In doing this I found, that the current implementation would return a string twice, if it does not contain delimiters and the tokenizer is asked to return the delimiters. This is cause by `Tokenize()` not returning or setting `tempstr` to empty after `if (tempstr.IndexOfAny(_delimiters.ToCharArray()) < 0 && tempstr.Length > 0)`, so that it is added again by the last `if` in that method.
=> Rework Tokenizer

build/Novell.Directory.Ldap.NETStandard.ruleset, src/Novell.Directory.Ldap.NETStandard/LdapEntry.cs, src/Novell.Directory.Ldap.NETStandard/Novell.Directory.Ldap.NETStandard.csproj, test/Novell.Directory.Ldap.NETStandard.UnitTests/LdapEntryTests.cs
As discussed in #264
Also set nullable compiler flag to "disable". This is the same as omitting it, just making it more clear as nullable gets implemented.
=> Add nullable reference types to LdapEntry.cs

src/Novell.Directory.Ldap.NETStandard/Asn1/Asn1Structured.cs, src/Novell.Directory.Ldap.NETStandard/LdapAttribute.cs, src/Novell.Directory.Ldap.NETStandard/LdapExtendedOperation.cs, src/Novell.Directory.Ldap.NETStandard/Novell.Directory.Ldap.NETStandard.csproj, src/Novell.Directory.Ldap.NETStandard/Utilclass/ByteArrayAsUtf8StringView.cs, src/Novell.Directory.Ldap.NETStandard/Utilclass/ByteArrayView.cs, src/Novell.Directory.Ldap.NETStandard/Utilclass/ViewBase.cs
Especially when interacting with LdapAttribute currently many copies are made. Introducing ByteArrayView and ByteArrayAsUtf8StringView allows us to give out IReadOnlyList-Representations of the values, without copying them before they are actually accessed. In addition I tried to reduce the amount of code used to resize and copy arrays, where the runtime now provides ways to do so.
=> Try to copy less

src/Novell.Directory.Ldap.NETStandard/LdapExtensions/ExtensionRegistrations.cs, src/Novell.Directory.Ldap.NETStandard/LdapExtensions/LdapKnownOids.cs, src/Novell.Directory.Ldap.NETStandard/LdapExtensions/LdapPasswordModifyOperation.cs, test/Novell.Directory.Ldap.NETStandard.FunctionalTests/ModifyPasswordTests.cs, test/Novell.Directory.Ldap.NETStandard.FunctionalTests/PasswordModifyExtendedOperationTests.cs
Adds support for the LDAP Password Modify Extended Operation specified in [RFC 3062](https://datatracker.ietf.org/doc/html/rfc3062).
I also added code to the functional tests to make sure this is working.  I haven't actually run the functional tests because I don't have Ubuntu or WSL right now...  and instead of just getting them I decided to be lazy and let the CI run the tests.  But I have built the library and written some external code that uses this and I can confirm that it works with OpenLDAP.
=> feat: Implement LDAP Password Modify Extended Operation
